
export const cssTools = [
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Compress and optimize your CSS code. Remove comments, whitespace, and unnecessary characters.',
    icon: 'fa-brands fa-css3-alt',
    color: '#3b82f6',
    badge: '',
    href: '/css-minifier',
  },
  {
    id: 'css-beautifier',
    name: 'CSS Beautifier',
    description: 'Format and prettify your CSS code. Make it readable with proper indentation and structure.',
    icon: 'fa-solid fa-brush',
    color: '#60a5fa',
    badge: '',
    href: '/css-beautifier',
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create beautiful CSS gradients with multiple stops. Preview and copy the code instantly.',
    icon: 'fa-solid fa-fill-drip',
    color: '#8b5cf6',
    badge: '',
    href: '/gradient-generator',
  },
  {
    id: 'box-shadow-generator',
    name: 'Box Shadow Generator',
    description: 'Design and preview CSS box shadows with real-time controls for offset, blur, and color.',
    icon: 'fa-solid fa-cube',
    color: '#f59e0b',
    badge: '',
    href: '/box-shadow-generator',
  },
  {
    id: 'svg-to-css',
    name: 'SVG to CSS Converter',
    description: 'Convert SVG to CSS background images or inline styles.',
    icon: 'fa-solid fa-image',
    color: '#f59e0b',
    badge: '',
    href: '/svg-to-css',
  },
]

export const jsTools = [
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier',
    description: 'Minify your JavaScript code. Optimize for production with advanced compression techniques.',
    icon: 'fa-brands fa-js',
    color: '#fbbf24',
    badge: 'New',
    href: '/js-minifier',
  },
  {
    id: 'js-beautifier',
    name: 'JavaScript Beautifier',
    description: 'Format and prettify your JavaScript code. Make it readable with proper indentation.',
    icon: 'fa-solid fa-brush',
    color: '#fcd34d',
    badge: '',
    href: '/js-beautifier',
  },
  {
    id: 'html-to-jsx',
    name: 'HTML to JSX Converter',
    description: 'Convert HTML to JSX for use in React applications. Supports complex nested structures.',
    icon: 'fa-brands fa-react',
    color: '#61dafb',
    badge: '',
    href: '/html-to-jsx',
  },
  {
    id: 'curl-to-code',
    name: 'cURL to Code',
    description: 'Convert cURL commands to code in JavaScript, Python, PHP, and more languages.',
    icon: 'fa-solid fa-terminal',
    color: '#0f1724',
    badge: '',
    href: '/curl-to-code',
  },
]

export const htmlTools = [
  {
    id: 'html-minifier',
    name: 'HTML Minifier',
    description: 'Clean and compress HTML markup. Reduce file size while maintaining functionality.',
    icon: 'fa-brands fa-html5',
    color: '#f97316',
    badge: 'Beta',
    href: '/html-minifier',
  },
  {
    id: 'html-beautifier',
    name: 'HTML Beautifier',
    description: 'Format and prettify your HTML code. Make it readable with proper indentation.',
    icon: 'fa-solid fa-brush',
    color: '#fb923c',
    badge: '',
    href: '/html-beautifier',
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown to HTML instantly. Preview the result in real-time.',
    icon: 'fa-solid fa-markdown',
    color: '#6b7280',
    badge: '',
    href: '/markdown-to-html',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Create favicons from any image. Generate all sizes and formats for your website.',
    icon: 'fa-solid fa-star',
    color: '#f59e0b',
    badge: '',
    href: '/favicon-generator',
  },
]

export const dataTools = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data. Make your JSON readable and debug with ease.',
    icon: 'fa-solid fa-file',
    color: '#8b5cf6',
    badge: '',
    href: '/json-formatter',
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format, validate, and minify XML data. Make your XML readable and debug with ease.',
    icon: 'fa-solid fa-code',
    color: '#f97316',
    badge: '',
    href: '/xml-formatter',
  },
  {
    id: 'yaml-formatter',
    name: 'YAML Formatter',
    description: 'Format and validate YAML data. Perfect for configuration files.',
    icon: 'fa-solid fa-code',
    color: '#14b8a6',
    badge: '',
    href: '/yaml-formatter',
  },
  {
    id: 'csv-formatter',
    name: 'CSV Formatter',
    description: 'Format and validate CSV data. Preview tables and handle delimiters.',
    icon: 'fa-solid fa-table',
    color: '#6366f1',
    badge: '',
    href: '/csv-formatter',
  },
  {
    id: 'toml-formatter',
    name: 'TOML Formatter',
    description: 'Format and validate TOML configuration files.',
    icon: 'fa-solid fa-cog',
    color: '#6b7280',
    badge: '',
    href: '/toml-formatter',
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON Converter',
    description: 'Convert XML data to JSON format. Transform structured data easily.',
    icon: 'fa-solid fa-arrows-h',
    color: '#8b5cf6',
    badge: '',
    href: '/xml-to-json',
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON Converter',
    description: 'Convert YAML data to JSON format. Great for configuration migration.',
    icon: 'fa-solid fa-arrows-h',
    color: '#10b981',
    badge: '',
    href: '/yaml-to-json',
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML Converter',
    description: 'Convert JSON data to XML format. Maintains structure and attributes.',
    icon: 'fa-solid fa-code',
    color: '#3b82f6',
    badge: '',
    href: '/json-to-xml',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON Converter',
    description: 'Convert CSV data to JSON format with configurable delimiters and structure.',
    icon: 'fa-solid fa-table',
    color: '#10b981',
    badge: '',
    href: '/csv-to-json',
  },
  {
    id: 'toml-json-converter',
    name: 'TOML to JSON Converter',
    description: 'Convert TOML configuration files to JSON and vice versa.',
    icon: 'fa-solid fa-cog',
    color: '#6b7280',
    badge: '',
    href: '/toml-json-converter',
  },
  {
    id: 'php-json-converter',
    name: 'PHP Array to JSON',
    description: 'Convert PHP arrays/serialized data to JSON format and vice versa.',
    icon: 'fa-brands fa-php',
    color: '#777bb4',
    badge: '',
    href: '/php-json-converter',
  },
  {
    id: 'json-schema-generator',
    name: 'JSON Schema Generator',
    description: 'Generate JSON Schema from your JSON data. Validate and document your API responses.',
    icon: 'fa-solid fa-diagram-project',
    color: '#8b5cf6',
    badge: '',
    href: '/json-schema-generator',
  },
]

export const encoderTools = [
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode text or files to Base64 format. Essential for data transmission.',
    icon: 'fa-solid fa-lock',
    color: '#3b82f6',
    badge: '',
    href: '/base64-encoder',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URLs for safe transmission. Handle special characters properly.',
    icon: 'fa-solid fa-link',
    color: '#06b6d4',
    badge: '',
    href: '/url-encoder',
  },
  {
    id: 'html-encoder',
    name: 'HTML Entity Encoder/Decoder',
    description: 'Convert HTML entities to characters and vice versa. Handle special characters.',
    icon: 'fa-solid fa-tags',
    color: '#f97316',
    badge: '',
    href: '/html-encoder',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JWT tokens. View header, payload, and signature details.',
    icon: 'fa-solid fa-key',
    color: '#8b5cf6',
    badge: '',
    href: '/jwt-decoder',
  },
  {
    id: 'jwt-generator',
    name: 'JWT Generator',
    description: 'Generate and sign JWT tokens with custom payload and expiration.',
    icon: 'fa-solid fa-key',
    color: '#ec4899',
    badge: '',
    href: '/jwt-generator',
  },
  {
    id: 'unicode-converter',
    name: 'Unicode Converter',
    description: 'Convert between Unicode, UTF-8, UTF-16, and other encodings.',
    icon: 'fa-solid fa-language',
    color: '#8b5cf6',
    badge: '',
    href: '/unicode-converter',
  },
  {
    id: 'ascii-converter',
    name: 'ASCII Converter',
    description: 'Convert text to ASCII codes and vice versa. Perfect for binary data handling.',
    icon: 'fa-solid fa-code',
    color: '#f97316',
    badge: '',
    href: '/ascii-converter',
  },
  {
    id: 'mime-type-validator',
    name: 'MIME Type Validator',
    description: 'Validate and lookup MIME types for files and content types.',
    icon: 'fa-solid fa-file',
    color: '#14b8a6',
    badge: '',
    href: '/mime-type-validator',
  },
]

export const generatorTools = [
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v4, v5, and other versions. Perfect for unique identifiers.',
    icon: 'fa-solid fa-id-card',
    color: '#8b5cf6',
    badge: '',
    href: '/uuid-generator',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, secure passwords with customizable length and character sets.',
    icon: 'fa-solid fa-key',
    color: '#ef4444',
    badge: '',
    href: '/password-generator',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text, URLs, or any data. Download in multiple formats.',
    icon: 'fa-solid fa-qrcode',
    color: '#059669',
    badge: '',
    href: '/qr-generator',
  },
  {
    id: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    description: 'Generate robots.txt files for your website. Control search engine crawling.',
    icon: 'fa-solid fa-robot',
    color: '#6b7280',
    badge: '',
    href: '/robots-txt-generator',
  },
  {
    id: 'sitemap-generator',
    name: 'Sitemap Generator',
    description: 'Generate XML sitemaps for your website. Help search engines index your pages.',
    icon: 'fa-solid fa-sitemap',
    color: '#3b82f6',
    badge: '',
    href: '/sitemap-generator',
  },
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers, strings, or hex values. Customize range and count.',
    icon: 'fa-solid fa-dice',
    color: '#f59e0b',
    badge: '',
    href: '/random-number-generator',
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Generator',
    description: 'Generate and validate cron expressions. Visualize schedule with human-readable format.',
    icon: 'fa-solid fa-calendar-alt',
    color: '#14b8a6',
    badge: '',
    href: '/cron-generator',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Generate various barcode formats (EAN-13, CODE128, etc.). Perfect for inventory and labels.',
    icon: 'fa-solid fa-barcode',
    color: '#3b82f6',
    badge: '',
    href: '/barcode-generator',
  },
  {
    id: 'openapi-generator',
    name: 'OpenAPI Generator',
    description: 'Generate OpenAPI/Swagger documentation from your API code or JSON data.',
    icon: 'fa-solid fa-file-code',
    color: '#10b981',
    badge: '',
    href: '/openapi-generator',
  },
  {
    id: 'mock-api-generator',
    name: 'Mock API Generator',
    description: 'Generate mock REST API endpoints with realistic data for testing and development.',
    icon: 'fa-solid fa-server',
    color: '#06b6d4',
    badge: '',
    href: '/mock-api-generator',
  },
]

export const textTools = [
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with real-time matching and replacement.',
    icon: 'fa-solid fa-code',
    color: '#06b6d4',
    badge: '',
    href: '/regex-tester',
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Convert text between cases: UPPER, lower, Title, Sentence, camelCase, snake_case, and more.',
    icon: 'fa-solid fa-font',
    color: '#14b8a6',
    badge: '',
    href: '/text-case-converter',
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in your text. Get detailed statistics.',
    icon: 'fa-solid fa-calculator',
    color: '#8b5cf6',
    badge: '',
    href: '/word-counter',
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare two texts and see the differences highlighted side by side.',
    icon: 'fa-solid fa-code-branch',
    color: '#f59e0b',
    badge: '',
    href: '/diff-checker',
  },
  {
    id: 'json-diff',
    name: 'JSON Diff Checker',
    description: 'Compare two JSON objects and see the differences in structure and values.',
    icon: 'fa-solid fa-code',
    color: '#8b5cf6',
    badge: '',
    href: '/json-diff',
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for your designs and mockups. Customize length and format.',
    icon: 'fa-solid fa-paragraph',
    color: '#6366f1',
    badge: '',
    href: '/lorem-ipsum',
  },
  {
    id: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    description: 'Remove duplicate lines from text. Keep only unique entries.',
    icon: 'fa-solid fa-eraser',
    color: '#ef4444',
    badge: '',
    href: '/remove-duplicate-lines',
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate URL-friendly slugs from any text. Perfect for SEO and URLs.',
    icon: 'fa-solid fa-link',
    color: '#14b8a6',
    badge: '',
    href: '/slug-generator',
  },
  {
    id: 'line-sorter',
    name: 'Line Sorter',
    description: 'Sort lines alphabetically, numerically, or reversed. Remove duplicates.',
    icon: 'fa-solid fa-sort',
    color: '#10b981',
    badge: '',
    href: '/line-sorter',
  },
]

export const converterTools = [
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between HEX, RGB, HSL, and more. Preview colors in real-time.',
    icon: 'fa-solid fa-palette',
    color: '#ec4899',
    badge: '',
    href: '/color-converter',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between units: length, weight, temperature, area, volume, and more.',
    icon: 'fa-solid fa-arrows-alt-h',
    color: '#10b981',
    badge: '',
    href: '/unit-converter',
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa.',
    icon: 'fa-solid fa-clock',
    color: '#f59e0b',
    badge: '',
    href: '/timestamp-converter',
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, hexadecimal, and other bases.',
    icon: 'fa-solid fa-rotate-right',
    color: '#6366f1',
    badge: '',
    href: '/number-base-converter',
  },
  {
    id: 'currenct-converter',
    name: 'Currency Converter',
    description: 'Convert between currencies with real-time exchange rates.',
    icon: 'fa-solid fa-dollar-sign',
    color: '#10b981',
    badge: '',
    href: '/currency-converter',
  },
  {
    id: 'file-size-converter',
    name: 'File Size Converter',
    description: 'Convert between B, KB, MB, GB, TB, PB. Understand file sizes easily.',
    icon: 'fa-solid fa-hdd',
    color: '#6b7280',
    badge: '',
    href: '/file-size-converter',
  },
  {
    id: 'roman-numeral',
    name: 'Roman Numeral Converter',
    description: 'Convert between Roman numerals and Arabic numbers.',
    icon: 'fa-solid fa-roman-numeral',
    color: '#8b5cf6',
    badge: '',
    href: '/roman-numeral',
  },
]

export const databaseTools = [
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries. Make your database code readable and consistent.',
    icon: 'fa-solid fa-database',
    color: '#06b6d4',
    badge: '',
    href: '/sql-formatter',
  },
  {
    id: 'docker-compose-converter',
    name: 'Docker Run to Compose',
    description: 'Convert Docker run commands to docker-compose.yml format.',
    icon: 'fa-brands fa-docker',
    color: '#2496ed',
    badge: '',
    href: '/docker-compose-converter',
  },
  {
    id: 'kubernetes-decoder',
    name: 'K8s Secret Decoder',
    description: 'Decode and inspect Kubernetes secrets. View base64 encoded data.',
    icon: 'fa-solid fa-cubes',
    color: '#326ce5',
    badge: '',
    href: '/kubernetes-decoder',
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate Unix/Linux file permission modes (755, 644, etc.) with visual feedback.',
    icon: 'fa-solid fa-terminal',
    color: '#0f1724',
    badge: '',
    href: '/chmod-calculator',
  },
  {
    id: 'subnet-calculator',
    name: 'Subnet Calculator',
    description: 'Calculate subnets, CIDR ranges, and IP addresses. Visualize network topology.',
    icon: 'fa-solid fa-network-wired',
    color: '#3b82f6',
    badge: '',
    href: '/subnet-calculator',
  },
]

export const securityTools = [
  {
    id: 'ssl-checker',
    name: 'SSL Checker',
    description: 'Check SSL/TLS certificate details. Verify expiration, issuer, and security protocols.',
    icon: 'fa-solid fa-shield-alt',
    color: '#10b981',
    badge: '',
    href: '/ssl-checker',
  },
  {
    id: 'password-strength',
    name: 'Password Strength Checker',
    description: 'Test password strength. Get feedback on security and suggestions for improvement.',
    icon: 'fa-solid fa-lock',
    color: '#ef4444',
    badge: '',
    href: '/password-strength',
  },
  {
    id: 'email-validator',
    name: 'Email Validator',
    description: 'Validate email addresses. Check format, domain, and deliverability.',
    icon: 'fa-solid fa-envelope',
    color: '#3b82f6',
    badge: '',
    href: '/email-validator',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes from your text.',
    icon: 'fa-solid fa-fingerprint',
    color: '#ec4899',
    badge: '',
    href: '/hash-generator',
  },
  {
    id: 'hash-verifier',
    name: 'Hash Verifier',
    description: 'Verify file or text integrity by comparing hash values. Support MD5, SHA-1, SHA-256.',
    icon: 'fa-solid fa-check-double',
    color: '#8b5cf6',
    badge: '',
    href: '/hash-verifier',
  },
  {
    id: 'rsa-key-generator',
    name: 'RSA Key Pair Generator',
    description: 'Generate RSA public/private key pairs for encryption and digital signatures.',
    icon: 'fa-solid fa-lock',
    color: '#ef4444',
    badge: '',
    href: '/rsa-key-generator',
  },
  {
    id: 'bcrypt-generator',
    name: 'Bcrypt Generator',
    description: 'Generate and verify bcrypt password hashes with configurable rounds.',
    icon: 'fa-solid fa-shield-alt',
    color: '#10b981',
    badge: '',
    href: '/bcrypt-generator',
  },
  {
    id: 'hmac-generator',
    name: 'HMAC Generator',
    description: 'Generate HMAC hashes for API authentication and message verification.',
    icon: 'fa-solid fa-fingerprint',
    color: '#3b82f6',
    badge: '',
    href: '/hmac-generator',
  },
  {
    id: 'aes-encryptor',
    name: 'AES Encryptor/Decryptor',
    description: 'Encrypt and decrypt text using AES-256-GCM or other modes.',
    icon: 'fa-solid fa-lock',
    color: '#8b5cf6',
    badge: '',
    href: '/aes-encryptor',
  },
  {
    id: 'certificate-decoder',
    name: 'Certificate Decoder',
    description: 'Decode and inspect SSL/TLS certificates. View expiration, issuer, and details.',
    icon: 'fa-solid fa-certificate',
    color: '#f59e0b',
    badge: '',
    href: '/certificate-decoder',
  },
]

export const dateTools = [
  {
    id: 'cron-validator',
    name: 'Cron Validator',
    description: 'Validate cron expressions and see next execution times.',
    icon: 'fa-solid fa-clock',
    color: '#f59e0b',
    badge: '',
    href: '/cron-validator',
  },
  {
    id: 'eta-calculator',
    name: 'ETA Calculator',
    description: 'Calculate estimated completion times for tasks based on progress.',
    icon: 'fa-solid fa-hourglass-half',
    color: '#3b82f6',
    badge: '',
    href: '/eta-calculator',
  },
  {
    id: 'date-difference',
    name: 'Date Difference Calculator',
    description: 'Calculate the difference between two dates in years, months, days.',
    icon: 'fa-solid fa-calendar-alt',
    color: '#8b5cf6',
    badge: '',
    href: '/date-difference',
  },
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    description: 'Convert time between different timezones around the world.',
    icon: 'fa-solid fa-globe',
    color: '#10b981',
    badge: '',
    href: '/timezone-converter',
  },
  {
    id: 'text-statistics',
    name: 'Text Statistics',
    description: 'Get detailed statistics about your text: words, characters, sentences, readability.',
    icon: 'fa-solid fa-calculator',
    color: '#6366f1',
    badge: '',
    href: '/text-statistics',
  },
]

export const networkTools = [
  {
    id: 'ip-lookup',
    name: 'IP Lookup',
    description: 'Get information about any IP address. Location, ISP, and more details.',
    icon: 'fa-solid fa-map-pin',
    color: '#8b5cf6',
    badge: '',
    href: '/ip-lookup',
  },
  {
    id: 'user-agent-parser',
    name: 'User Agent Parser',
    description: 'Parse and analyze user agent strings. Get browser, OS, and device information.',
    icon: 'fa-solid fa-user',
    color: '#06b6d4',
    badge: '',
    href: '/user-agent-parser',
  },
  {
    id: 'mac-lookup',
    name: 'MAC Address Lookup',
    description: 'Look up manufacturer information from MAC addresses (OUI lookup).',
    icon: 'fa-solid fa-ethernet',
    color: '#06b6d4',
    badge: '',
    href: '/mac-lookup',
  },
]

export const miscTools = [
  {
    id: 'http-status-codes',
    name: 'HTTP Status Codes',
    description: 'Reference guide for all HTTP status codes. Understand 1xx, 2xx, 3xx, 4xx, and 5xx codes.',
    icon: 'fa-solid fa-code',
    color: '#3b82f6',
    badge: '',
    href: '/http-status-codes',
  },
  {
    id: 'emoji-picker',
    name: 'Emoji Picker',
    description: 'Search and copy emojis for your projects. Search by category or keyword.',
    icon: 'fa-regular fa-face-smile',
    color: '#fbbf24',
    badge: '',
    href: '/emoji-picker',
  },
  {
    id: 'bip39-generator',
    name: 'BIP39 Mnemonic Generator',
    description: 'Generate BIP39 mnemonic phrases for cryptocurrency wallets and seed phrases.',
    icon: 'fa-solid fa-coins',
    color: '#f59e0b',
    badge: '',
    href: '/bip39-generator',
  },
  {
    id: 'benchmark-tool',
    name: 'Benchmark Tool',
    description: 'Measure the performance of your code or API endpoints. Get detailed metrics.',
    icon: 'fa-solid fa-chart-line',
    color: '#3b82f6',
    badge: '',
    href: '/benchmark-tool',
  },
]

export const colorTools = [
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between HEX, RGB, HSL, and more. Preview colors in real-time.',
    icon: 'fa-solid fa-palette',
    color: '#ec4899',
    badge: '',
    href: '/color-converter',
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create beautiful CSS gradients with multiple stops. Preview and copy the code instantly.',
    icon: 'fa-solid fa-fill-drip',
    color: '#8b5cf6',
    badge: '',
    href: '/gradient-generator',
  },
]

export const allTools = [
  ...cssTools,
  ...jsTools,
  ...htmlTools,
  ...dataTools,
  ...encoderTools,
  ...generatorTools,
  ...textTools,
  ...converterTools,
  ...databaseTools,
  ...securityTools,
  ...dateTools,
  ...networkTools,
  ...miscTools,
]

export const categories = [
  { id: 'css', name: 'CSS & Style', icon: 'fa-brands fa-css3-alt', color: '#3b82f6', tools: cssTools },
  { id: 'js', name: 'JavaScript', icon: 'fa-brands fa-js',color: '#f97316' ,tools: jsTools },
  { id: 'html', name: 'HTML & Markup', icon: 'fa-brands fa-html5', color:'#ea580c', tools: htmlTools },
  { id: 'data', name: 'JSON, YAML, XML, CSV', icon: 'fa-solid fa-file', color: '#22c55e', tools: dataTools },
  { id: 'encoder', name: 'Encoders & Decoders', icon: 'fa-solid fa-lock', color: '#ef4444',tools: encoderTools },
  { id: 'generator', name: 'Generators', icon: 'fa-solid fa-wand-magic-sparkles', color: '#eb78de',tools: generatorTools },
  { id: 'text', name: 'Text & String', icon: 'fa-solid fa-font', color: '#4c8f7',tools: textTools },
  { id: 'converter', name: 'Converters', icon: 'fa-solid fa-arrows-rotate', color: '#9bd5ed',tools: converterTools },
  { id: 'database', name: 'Database & DevOps', icon: 'fa-solid fa-database', color: '#75aaf5',tools: databaseTools },
  { id: 'security', name: 'Security & Crypto', icon: 'fa-solid fa-shield-halved', color: '#fbbf24',tools: securityTools },
  { id: 'date', name: 'Date & Time', icon: 'fa-solid fa-clock', color: '#55e5',tools: dateTools },
  { id: 'network', name: 'Network & Lookup', icon: 'fa-solid fa-network-wired', color: '#6afde',tools: networkTools },
  { id: 'misc', name: 'Miscellaneous', icon: 'fa-solid fa-ellipsis-h', color: '#7d7d7d',tools: miscTools },
]

export const quickTools = [
  { 
    name: 'CSS Minifier', 
    href: '/css-minifier', 
    icon: 'fa-brands fa-css3-alt', 
    color: '#3b82f6',
    description: 'Compress CSS'
  },
  { 
    name: 'JS Minifier', 
    href: '/js-minifier', 
    icon: 'fa-brands fa-js', 
    color: '#fbbf24',
    description: 'Minify JS'
  },
  { 
    name: 'HTML Minifier', 
    href: '/html-minifier', 
    icon: 'fa-brands fa-html5', 
    color: '#f97316',
    description: 'Compress HTML'
  },
  { 
    name: 'JSON Formatter', 
    href: '/json-formatter', 
    icon: 'fa-solid fa-file', 
    color: '#8b5cf6',
    description: 'Format JSON'
  },
  { 
    name: 'Color Converter', 
    href: '/color-converter', 
    icon: 'fa-solid fa-palette', 
    color: '#ec4899',
    description: 'Convert Colors'
  },
  { 
    name: 'Regex Tester', 
    href: '/regex-tester', 
    icon: 'fa-solid fa-code', 
    color: '#06b6d4',
    description: 'Test Regex'
  },
]
