
export const tools = [
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Compress and optimize your CSS code. Remove comments, whitespace, and unnecessary characters.',
    icon: 'fa-brands fa-css3-alt',
    color: '#3b82f6',
    badge: 'Popular',
    href: '/css-minifier',
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier',
    description: 'Minify your JavaScript code. Optimize for production with advanced compression techniques.',
    icon: 'fa-brands fa-js',
    color: '#fbbf24',
    badge: 'New',
    href: '/js-minifier',
  },
  {
    id: 'html-minifier',
    name: 'HTML Minifier',
    description: 'Clean and compress HTML markup. Reduce file size while maintaining functionality.',
    icon: 'fa-brands fa-html5',
    color: '#f97316',
    badge: 'Beta',
    href: '/html-minifier',
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format and validate JSON data. Make your JSON readable and debug with ease.',
    icon: 'fa-solid fa-brackets-curly',
    color: '#8b5cf6',
    badge: '',
    href: '/json-formatter',
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between HEX, RGB, HSL, and more. Preview colors in real-time.',
    icon: 'fa-solid fa-palette',
    color: '#ec4899',
    badge: '',
    href: '/color-converter',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with real-time matching and replacement.',
    icon: 'fa-solid fa-code',
    color: '#06b6d4',
    badge: '',
    href: '/regex-tester',
  },
]
